Script started on 2020-03-05 14:34:18-0500
]0;djv78@gold21: ~/CS214Work/214/labs/05/clojure[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/clojure[00m$ cat sp[K[Ksrc/split.clj 
;;;; split.clj splits a string into two substrings.
;;;;
;;;; Input: aString, the string to be split,
;;;;        pos, the index where aString is to be split.
;;;; Output: the substring of aString before pos, and
;;;;         the substring of aString from pos onwards.
;;;;
;;;; Usage: clojure -m split
;;;;
;;;; Begun by: Dr. Adams, for CS 214 at Calvin College.
;;;; Completed by: Duncan Van Keulen
;;;; Date: 2-5-2020
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns split)      ; name the program

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; split() splits a string into its two substrings.  
;;; Receive: aString, the string to be split,         
;;;          splitPos, the index where aString should be split.
;;; PRE: 0 <= splitPos < the length of aString.
;;; Return: the substring of aString before pos, and  
;;;         the substring of aString from pos onwards.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defn split [aString splitPos]
  (let [firstPart (subs aString 0 splitPos) ;; bind firstPart
        length (count aString)              ;; bind the length of the string
        lastPart (subs aString splitPos length) ;; bind lastPart
        ]
    (vector firstPart lastPart)
  )
)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; main function
;;; Input: the string to be split,
;;;        the index where it should be split.
;;; Output: the two split parts of the string.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defn -main []
  (print "To split a string, enter the string: ") (flush)
  (let
    [ aString (read-line) ]                      ; read the string
    (print "Enter the split position: ") (flush)
    (let 
      [ pos (read)                               ; read the split pos.
        result (split aString pos)               ; split the string
        part1 (get result 0)                     ; retrieve the two
        part2 (get result 1)                     ;  parts
      ]
                                                 ; display the parts
      (printf (str "\nThe first part is \"%s\" and" 
                    " the second part is \"%s\"\n\n")
                       part1 part2)
    )
  )
)

]0;djv78@gold21: ~/CS214Work/214/labs/05/clojure[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/clojure[00m$ clojure -m split
To split a string, enter the string: hello
Enter the split position: 0

The first part is "" and the second part is "hello"

]0;djv78@gold21: ~/CS214Work/214/labs/05/clojure[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/clojure[00m$ clojure -m split
To split a string, enter the string: hgell    ello
Enter the split position: 3

The first part is "hel" and the second part is "lo"

]0;djv78@gold21: ~/CS214Work/214/labs/05/clojure[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/clojure[00m$ clojure -m split
To split a string, enter the string: hello
Enter the split position: 5

The first part is "hello" and the second part is ""

]0;djv78@gold21: ~/CS214Work/214/labs/05/clojure[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/clojure[00m$ exit

Script done on 2020-03-05 14:35:08-0500
