Script started on 2020-02-27 13:28:26-0500
]0;djv78@gold07: ~/CS214Work/214/labs/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/java[00m$ cat T[KLogTable.java
/* LogTable.java displays a table of logarithms.
 *
 * Input: start, stop and increment, three doubles.
 * PRE: start < stop && increment > 0.
 * Output: A table of logarithms from start to stop,
 *         with increment as the step value.
 * Begun by: Nelesen, for CS 214 at Calvin College.
 * Completed by: Duncan Van Keulen on 2-27-2020
 ********************************************************/
import java.util.Scanner; 		// Get input

class LogTable{

  public static void main(String[] args){
    Scanner keyboard = new Scanner(System.in);
    System.out.println("To display a table of logarithms,");
    System.out.println("enter the start, stop and increment values: ");
    double start, stop, increment;
    start = keyboard.nextDouble();
    stop = keyboard.nextDouble();
    increment = keyboard.nextDouble();

    //Replace this line with a while loop to generate the table of logs
    for(double i = start; i <= stop; i += increment) {
      // print out the logarithm in a readable format
      System.out.println("The logarithm of " + i + " is " + java.lang.Math.log10(i));
    }
  }
}

]0;djv78@gold07: ~/CS214Work/214/labs/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/java[00m$ javac-[K -deprecation LogTable.java 
]0;djv78@gold07: ~/CS214Work/214/labs/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/java[00m$ java LogTable 
To display a table of logarithms,
enter the start, stop and increment values: 
1
2
.5
The logarithm of 1.0 is 0.0
The logarithm of 1.5 is 0.17609125905568124
The logarithm of 2.0 is 0.3010299956639812
]0;djv78@gold07: ~/CS214Work/214/labs/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/java[00m$ java LogTable 
To display a table of logarithms,
enter the start, stop and increment values: 
10 =  0
20
5
The logarithm of 0.0 is -Infinity
The logarithm of 5.0 is 0.6989700043360189
The logarithm of 10.0 is 1.0
The logarithm of 15.0 is 1.1760912590556813
The logarithm of 20.0 is 1.3010299956639813
]0;djv78@gold07: ~/CS214Work/214/labs/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/java[00m$ exit

Script done on 2020-02-27 13:29:24-0500
