Script started on 2020-03-13 12:01:21-0400
]0;djv78@gold14: ~/CS214Work/214/projects/06/ruby[01;32mdjv78@gold14[00m:[01;34m~/CS214Work/214/projects/06/ruby[00m$ cat array_util.rb 
# array_util.rb implements filling an array with user vals and printing that array
# 
# Input: user values into the array
# Output: the values of the array
#
# By: Duncan Van Keulen
# Date: 3-12-2020
########################################################

###############################################
# readArray() reads in values from a user and puts them in an array
# Receive: anArray, an array of numbers
# Recieve: itsSize, the size of the array
################################################

def readArray(anArray, itsSize)
    i = 0
    until i >= itsSize do
        anArray[i] = gets.to_f
        i = i + 1
    end
    return anArray
end

###############################################
# printArray() outputs the contents of the array separated by newlines
# Receive: anArray, an array of numbers
################################################

def printArray(anArray, itsSize)
    anArray.each { |element| puts element}
end


# Main driver
def main
    # Get size
    print("Enter the size of the array: ")
    itsSize = gets.to_f

    theArray = Array.new(itsSize){}
    print("Enter the values of the array: ")
    theArray = readArray(theArray, itsSize)
    puts("The values of the array are...")
    printArray(theArray, itsSize)

end

main
]0;djv78@gold14: ~/CS214Work/214/projects/06/ruby[01;32mdjv78@gold14[00m:[01;34m~/CS214Work/214/projects/06/ruby[00m$ ruby array_util.rb 
Enter the size of the array: 5
Enter the values of the array: 1
2
3
4
5
The values of the array are...
1.0
2.0
3.0
4.0
5.0
]0;djv78@gold14: ~/CS214Work/214/projects/06/ruby[01;32mdjv78@gold14[00m:[01;34m~/CS214Work/214/projects/06/ruby[00m$ ruby array_util.rb 
Enter the size of the array: 2
Enter the values of the array: 1
2
The values of the array are...
1.0
2.0
]0;djv78@gold14: ~/CS214Work/214/projects/06/ruby[01;32mdjv78@gold14[00m:[01;34m~/CS214Work/214/projects/06/ruby[00m$ ruby array_util.rb 
Enter the size of the array: 3
Enter the values of the array: 123456789
987654321
5.5
The values of the array are...
123456789.0
987654321.0
5.5
]0;djv78@gold14: ~/CS214Work/214/projects/06/ruby[01;32mdjv78@gold14[00m:[01;34m~/CS214Work/214/projects/06/ruby[00m$ exit

Script done on 2020-03-13 12:03:58-0400
