Script started on 2020-03-12 15:48:28-0400
]0;djv78@gold21: ~/CS214Work/214/projects/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/projects/06/ada[00m$ cat array_util.adb
-- array_util.adb implements a driver and funcitons for reading 
--      and printing arrays of values
--
-- Input: User must input size and values of arrays
-- 
-- Output: The values input to the array will be printed back wiht newlines
--
-- By: Duncan Van Keulen
-- Date: 3-5-2020
--------------------------------------------------------------

with Ada.Float_Text_IO, Ada.Text_IO, Ada.Integer_Text_IO;
use Ada.Float_Text_IO, Ada.Text_IO, Ada.Integer_Text_IO;

procedure array_util is

    type Vector is array ( Positive range <> ) of Float;

    its_size : Integer;

----------------------------------------------
-- Fill_Array fills an array with values from the user
-- Receive: anArray, an empty array
----------------------------------------------
procedure Fill_Array(an_array : in out Vector; its_size : in Integer) is
    val : Float;
begin
    for i in 1..its_size loop
        Get(val);
        an_array(i) := val;
    end loop;
    
end Fill_Array;

----------------------------------------------
-- Print_Array prints the values in an array separated by newlines
-- Receive: anArray, an array with values
-- Precondiiton: anArray must have values
----------------------------------------------
procedure Print_Array(an_array : in Vector; its_size : in Integer) is
begin
    for i in 1..its_size loop
        Put(an_array(i));
        Put_Line("");
    end loop;

end Print_Array;

begin
    Put("Enter the size of the array: ");
    Get(its_size);

    declare
        an_array : Vector(1..its_size); -- declaring an empty array
    begin
        Put("Enter the array values: ");
        Fill_Array(an_array, its_size);
        Print_Array(an_array, its_size);
    end;



end array_util;


]0;djv78@gold21: ~/CS214Work/214/projects/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/projects/06/ada[00m$ gnatmake array_util.adb 
gnatmake: "array_util" up to date.
]0;djv78@gold21: ~/CS214Work/214/projects/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/projects/06/ada[00m$ ./array_util 
Enter the size of the array: 0
Enter the array values: 
]0;djv78@gold21: ~/CS214Work/214/projects/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/projects/06/ada[00m$ ./array_util 
Enter the size of the array: 5
Enter the array values: 12 
2
3
4
5
 1.00000E+00
 2.00000E+00
 3.00000E+00
 4.00000E+00
 5.00000E+00
]0;djv78@gold21: ~/CS214Work/214/projects/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/projects/06/ada[00m$ ./array_util 
Enter the size of the array: 3
Enter the array values: 100000
123456789
987654321
 1.00000E+05
 1.23457E+08
 9.87654E+08
]0;djv78@gold21: ~/CS214Work/214/projects/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/projects/06/ada[00m$ exit

Script done on 2020-03-12 15:49:25-0400
