Script started on 2020-02-27 16:05:39-0500
]0;djv78@gold07: ~/CS214Work/214/projects/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/java[00m$ cate[K Factorial.java
/* Factorial.java outputs n! of the input number
 *
 * Input: double n
 * Output: The factorial of the number
 * Duncan Van Keulen on 2-27-2020
 ********************************************************/
import java.util.Scanner;

class Factorial {
    public static void main(String[] args) {
        Scanner keyboard = new Scanner(System.in);
        System.out.print("Enter a number: ");
        double n; double answer = 1.0;

        n = keyboard.nextDouble();

        // Loop from 2 to n, multiplying each time to calculate factorial
        for(int i = 2; i <= n; i++) {
            answer *= i;
        } 
        System.out.println(n + "! = " + answer);
    }
}]0;djv78@gold07: ~/CS214Work/214/projects/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/java[00m$ javac -deprecation Factorial.java [K[K[K[K[K[K.java
]0;djv78@gold07: ~/CS214Work/214/projects/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/java[00m$ java a[KFactorial 
Enter a number: 2
2.0! = 2.0
]0;djv78@gold07: ~/CS214Work/214/projects/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/java[00m$ java Factorial 
Enter a number: 10  5
5.0! = 120.0
]0;djv78@gold07: ~/CS214Work/214/projects/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/java[00m$ java Factorial 
Enter a number: 3
3.0! = 6.0
]0;djv78@gold07: ~/CS214Work/214/projects/04/java[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/java[00m$ exit

Script done on 2020-02-27 16:06:36-0500
