Script started on 2020-04-23 18:50:41-0400
]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ ls
Bird.rb  birds.rb  Duck.rb  Goose.rb  Owl.rb  ruby.script
]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ cat Bird.rb
# Bird.rb | Defines a Bird superclass 
#   to be extended by specific bird sub-classes.
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date: 4/23/2020
####################################################

class Bird

    attr_reader :name

    def initialize(name)
        @name = name
    end

    def call
        'Squaaaaaaawk!'
        end
    
    def className
        self.class.to_s
    end

    def print
        puts name + " " + className + " says " + call
    end

end]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ cat Duck[KOwl.rb
# Owl.rb | Defines the Owl class which inherits attributes and methods
#   from the Bird superclass.
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date:4/23/2020
####################################################

require './Bird.rb'

class Owl < Bird

    def call
        'Whoo-hoo!'
    end

end]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ cat Duck.rb
# Duck.rb | Defines the Duck class which inherits attributes and methods
#   from the Bird superclass.
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date:4/23/2020
####################################################

require './Bird.rb'

class Duck < Bird

    def call
        'Quack!'
    end

end]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ cat Goose.rb
# Goose.rb | Defines the Goose class which inherits attributes and methods
#   from the Bird superclass.
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date:4/23/2020
####################################################

require './Bird.rb'

class Goose < Bird

    def call
        'Honk!'
    end

end]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ cat birds.rb
# birds.rb | Tests out the menagerie of bird classes.
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date: 4/23/2020
######################################################

require './Bird.rb'
require './Duck.rb'
require './Goose.rb'
require './Owl.rb'

puts "\nWelcome to the Bird Park!\n\n"

bird0 = Bird.new "Hawkeye"
bird0.print

bird1 = Duck.new "Donald"
bird1.print

bird2 = Goose.new "Mother"
bird2.print

bird3 = Owl.new "Woodsey"
bird3.print

puts "\n\n"]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ ruby birdd[Ks.rb

Welcome to the Bird Park!

Hawkeye Bird says Squaaaaaaawk!
Donald Duck says Quack!
Mother Goose says Honk!
Woodsey Owl says Whoo-hoo!


]0;djv78@gold33: ~/CS214Work/214/labs/10/ruby[01;32mdjv78@gold33[00m:[01;34m~/CS214Work/214/labs/10/ruby[00m$ exit

Script done on 2020-04-23 18:51:52-0400
