Script started on 2020-04-16 17:49:35-0400
]0;djv78@gold02: ~/CS214Work/214/labs/09/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/ruby[00m$ cat max.rb
# max.rb tests a Ruby linked list.
#
# Begun by: Dr. Adams for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date: 4/16/2020

require './List'

list1 = List.new
list2 = List.new
list3 = List.new

list1.append(99).append(88).append(77).append(66).append(55)
list2.append(55).append(66).append(77).append(88).append(99)
list3.append(55).append(77).append(99).append(88).append(66)

list1.print 
puts
puts "Maximum of list1: #{list1.max}"

list2.print 
puts
puts "Maximum of list2: #{list2.max}"

list3.print 
puts
puts "Maximum of list3: #{list3.max}"

]0;djv78@gold02: ~/CS214Work/214/labs/09/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/ruby[00m$ ruby max.rb
 99 88 77 66 55
Maximum of list1: 99
 55 66 77 88 99
Maximum of list2: 99
 55 77 99 88 66
Maximum of list3: 99
]0;djv78@gold02: ~/CS214Work/214/labs/09/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/ruby[00m$ exit

Script done on 2020-04-16 17:49:46-0400
