Script started on 2020-03-05 14:11:34-0500
]0;djv78@gold21: ~/CS214Work/214/labs/05/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/ada[00m$ cat split.adb
-- split.adb splits an input string about a specified position.
--
-- Input: Astring, a string,
--        Pos, an integer.
-- Precondition: pos is in Astring'Range.
-- Output: The substrings Astring(Astring'First..Pos-1) and
--                        Astring(Pos..Astring'Last).
--
-- Begun by: Dr. Adams, for CS 214 at Calvin College.
-- Completed by: Duncan Van Keulen
-- Date: 3-5-2020
--------------------------------------------------------------

with Ada.Text_IO, Ada.Integer_Text_IO, Ada.Strings.Fixed;
use  Ada.Text_IO, Ada.Integer_Text_IO, Ada.Strings.Fixed;

procedure split is

   EMPTY_STRING : String := "                                        ";

   Astring, Part1, Part2 : String  := EMPTY_STRING;
   Pos, Chars_read       : Natural;

   ------------------------------------------------
   --  split() splits a string in two.           
   -- Receive: The_String, the string to be split,
   --          Position, the split index.        
   -- PRE: 0 < Position <= The_String.length(). 
   --     (Ada arrays are 1-relative by default)
   -- Passback: First_Part - the first substring,
   --           Last_Part - the second substring.
   ------------------------------------------------
procedure split(The_String : in String; Pos : in out Natural; Part1 : out String; Part2 : out String) is
begin
   Move(The_String(The_String'First..Pos), Part1); -- Move the first part of the string into Part1
   Pos := Pos + 1;                                 -- Increment Pos as to not get overlapping parts
   Move(The_String(Pos..The_String'Last), Part2);  -- Move the second part of the string into Part2

end split;

begin                                           -- Prompt for input
   Put("To split a string, enter the string: ");
   Get_Line(Astring, Chars_Read);
   Put("Enter the split position: ");
   Get(Pos);

   split(Astring, Pos, Part1, Part2);

   Put("The first part is ");
   Put_Line(Part1);
   Put(" and the second part is ");
   Put_Line(Part2);

end split;

]0;djv78@gold21: ~/CS214Work/214/labs/05/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/ada[00m$ gnatmake d[Ksplit.adb 
gnatmake: "split" up to date.
]0;djv78@gold21: ~/CS214Work/214/labs/05/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/ada[00m$ ./split
To split a string, enter the string: hello
Enter the split position: 1
The first part is h                                       
 and the second part is ello                                    
]0;djv78@gold21: ~/CS214Work/214/labs/05/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/ada[00m$ ./split
To split a string, enter the string: hello
Enter the split position: 4
The first part is hell                                    
 and the second part is o                                       
]0;djv78@gold21: ~/CS214Work/214/labs/05/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/ada[00m$ ./split
To split a string, enter the string: hello
Enter the split position: 6
The first part is hello                                   
 and the second part is                                         
]0;djv78@gold21: ~/CS214Work/214/labs/05/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/ada[00m$ exit

Script done on 2020-03-05 14:12:13-0500
