Script started on 2020-04-16 17:49:54-0400
]0;djv78@gold02: ~/CS214Work/214/labs/09/clojure[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/clojure[00m$ cat src/max.clj 
;; max.clj tests a function to search a list for its maximum value.
;;
;; Output: three lists, and 
;;          the results of calling a maxList() function on them.
;;
;; Usage: clojure -m max
;;
;; Begun by: Dr. Adams, CS 214 at Calvin College.
;; Completed by: Duncan Van Keulen
;; Date: 4/16/2020
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns max)

(load "listOps")                      ; load module

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Function -main tests function listMax(). 
;; Output: the results of testing listMax() on various lists.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defn -main []
  (let
    [ 
      list1 '(99 88 77 66 55)        ; max is first value
      list2 (list 55 66 77 88 99)    ; max is last value
      list3 (list 55 77 99 88 66)    ; max is middle value
      emptyList '()                  ; list is empty
    ]

    (println)
    (println "list1: " list1)        ; print list1,
    (println "list2: " list2)        ;   list2,
    (println "list3: " list3)        ;   list3,
    (println "empty: " emptyList)    ;   list3,
    (println)                        ;   and their maxima
    (println "The max value in list1 is: " (listMax list1))
    (println "The max value in list2 is: " (listMax list2))
    (println "The max value in list3 is: " (listMax list3))
    (println)
    (println "The max of an empty list is: " (listMax emptyList))
    (println)

    (println "The max value in list1 using listMax2 is: " (listMax2 list1))
    (println "The max value in list2 using listMax2 is: " (listMax2 list2))
    (println "The max value in list3 using listMax2 is: " (listMax2 list3))
    (println)
    (println "The max of an empty list using listMax2 is is: " (listMax2 emptyList))
    (println)
  )
)

]0;djv78@gold02: ~/CS214Work/214/labs/09/clojure[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/clojure[00m$ make
clojure -m max

list1:  (99 88 77 66 55)
list2:  (55 66 77 88 99)
list3:  (55 77 99 88 66)
empty:  ()

The max value in list1 is:  99
The max value in list2 is:  99
The max value in list3 is:  99

The max of an empty list is:  nil

The max value in list1 using listMax2 is:  99
The max value in list2 using listMax2 is:  99
The max value in list3 using listMax2 is:  99

The max of an empty list using listMax2 is is:  nil

]0;djv78@gold02: ~/CS214Work/214/labs/09/clojure[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/clojure[00m$ exit

Script done on 2020-04-16 17:50:09-0400
