Script started on 2020-04-09 11:40:37-0400
l]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ ls
java.script  Makefile  Name.class  Name.java  NameTester.class  [0m[01;32mNameTester.java[0m
]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ cat Name.jva[K[Kava
/* Name.java implements class Name.
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Student: Duncan Van Keulen
 * Date: 2/9/2020
 ************************************************************/


// the Name class appears outside of the rest of the program
class Name {

    // Name object constructor with initialization
    public Name(final String first, final String middle, final String last) {
        myFirst = first;
        myMiddle = middle;
        myLast = last;
    }

    // extractor for first name of a Name object
    public final String getFirst() {
        return myFirst;
    }

    // extractor for middle name of a Name object
    public final String getMiddle() {
        return myMiddle;
    }

    // extractor for last name of a Name object
    public final String getLast() {
        return myLast;
    }

    // return string created by piecing together first, middle, and last names
    public final String toString() {
        return myFirst + ' ' + myMiddle + ' ' + myLast;
    }

    private String myFirst, myMiddle, myLast; // private instance variables
}]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ cat NameTester.java
/* NameTester.java is a 'driver' to test class Name.
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Student:Duncan Van Keulen
 * Date: 4/9/2020
 ************************************************************/

public class NameTester {
    public static void main(String[] args) {
        Name aName = new Name("John", "Paul", "Jones");

        assert aName.getFirst().equals("John");
        assert aName.getMiddle().equals("Paul");
        assert aName.getLast().equals("Jones");

        System.out.println(aName);
        assert aName.toString().equals("John Paul Jones");

        System.out.println("All tests passed!");
    }
}


]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ make java
make: *** No rule to make target 'java'.  Stop.
]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ j[Kmake
make: Nothing to be done for 'NameTester'.
]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ javac 0-[K[K-deprecation Name.java
]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ java NameTester
John Paul Jones
All tests passed!
]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ java -ea name[K[K[K[KNameTester
John Paul Jones
All tests passed!
]0;djv78@gold02: ~/CS214Work/214/labs/08/java[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/java[00m$ exit

Script done on 2020-04-09 11:41:34-0400
