Script started on 2020-04-09 13:47:14-0400
]0;djv78@gold02: ~/CS214Work/214/labs/08/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/ruby[00m$ ls
Names.rb  nameTester.rb  ruby.script
]0;djv78@gold02: ~/CS214Work/214/labs/08/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/ruby[00m$ cad[Kt Names.rb
# Name class module file
# Duncan Van Keulen for CS214 Lab08
####################################

class Name

    def initialize(first, middle, last)
        @first, @middle, @last = first, middle, last
    end

attr_reader :first, :middle, :last

    def fullName
        @first + " " + @middle + " " + @last
    end

    def print
        puts fullName
        fullName
    end
end]0;djv78@gold02: ~/CS214Work/214/labs/08/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/ruby[00m$ cat nameTester.rb 
# nameTester.rb tests class Name and its operations
#
# Begun by: Dr. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen
# Date: 4/9/2020
####################################################

require 'test/unit/assertions'
load "Names.rb"
include Test::Unit::Assertions

def testName
    name = Name.new("John", "Paul", "Jones")

    assert name.first == "John", 
        "first failed"
    assert name.middle == "Paul",
        "middle failed"
    assert name.last == "Jones",
        "last failed"
    assert name.fullName == "John Paul Jones",
        "fullName failed"
    assert name.print == "John Paul Jones",
        "print failed"

    print "All tests passed!\n"
end

testName

]0;djv78@gold02: ~/CS214Work/214/labs/08/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/ruby[00m$ ruby nameTester
[1mTraceback[m (most recent call last):
ruby: [1mNo such file or directory -- nameTester ([1;4mLoadError[m[1m)
[m]0;djv78@gold02: ~/CS214Work/214/labs/08/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/ruby[00m$ ruby N[KnameTester.rb 
John Paul Jones
All tests passed!
]0;djv78@gold02: ~/CS214Work/214/labs/08/ruby[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/08/ruby[00m$ exit

Script done on 2020-04-09 13:47:45-0400
