Script started on 2020-03-12 14:10:37-0400
]0;djv78@gold21: ~/CS214Work/214/labs/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/06/ada[00m$ cat average.adb
-- average.adb "test-drives" function Average.
-- Precondition: theArray is an array of numbers.
-- Output: the average of the numbers.
--
-- Begun by: Dr. Adams, CS 214 at Calvin College.
-- Completed by: Duncan Van Keulen
-- Date: 3-12-2020
-----------------------------------------------

with Ada.Text_IO; use Ada.Text_IO;             -- Put(String)
with Ada.Float_Text_IO; use Ada.Float_Text_IO; -- Put(Float)

procedure average is

-- Declare Vector type
type vector is array ( Positive range <> ) of Float;

-- Define array0 as an array containing no values
array0 : Vector := (0.0, 0.0);

-- Define array1 as an array containing 9, 8, 7, 6
array1 : Vector := (9.0, 8.0, 7.0, 6.0);


----------------------------------------------
-- sum() sums the values in an array           -
-- Receive: anArray, an array of numbers     -
-- Return: the sum of the values in anArray. -
----------------------------------------------

function sum(A : in Vector) return Float is
   Total : Float := 0.0; 
   begin 
      --for I in A'Range 
      -- Using a constrained range
      for I in 1..A'Length
      loop 
         Total := Total + A(I);
      end loop; 
      return Total; 
   end sum; 

----------------------------------------------
-- average() computes the average of the values in an array           
-- Receive: A, an array (vector) of numbers     
-- Return: the average of the values in A. 
----------------------------------------------
function average(A : in Vector) return Float is
   begin
      return sum(A) / Float(A'Length);
   end average;

begin
   Put(" average 0 is ");
   Put( average(array0) );
   New_line;
   Put(" average 1 is ");
   Put( average(array1) );
   New_line;
end average;

]0;djv78@gold21: ~/CS214Work/214/labs/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/06/ada[00m$ make average
gnatmake average.adb
x86_64-linux-gnu-gcc-7 -c average.adb
x86_64-linux-gnu-gnatbind-7 -x average.ali
x86_64-linux-gnu-gnatlink-7 average.ali
]0;djv78@gold21: ~/CS214Work/214/labs/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/06/ada[00m$ ./average
 average 0 is  0.00000E+00
 average 1 is  7.50000E+00
]0;djv78@gold21: ~/CS214Work/214/labs/06/ada[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/06/ada[00m$ exit

Script done on 2020-03-12 14:10:46-0400
