Script started on 2020-03-09 19:04:45-0400
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ cat roots.adb
-- roots.adb calculates quadratic roots.
--
-- Input: A, B, C : floats corresponding to A, B, C in quadratic equation
--        
-- Precondition: A is positive, b^2 - 4 * a * c is positive
-- Output: root1, root2 : floats, the roots fo the quadratic function
--
-- By: Duncan Van Keulen
-- Date: 3-9-2020
--------------------------------------------------------------

with Ada.Float_Text_IO, Ada.Text_IO, Ada.Numerics.Generic_Complex_Elementary_Functions,
    Ada.Numerics.Elementary_Functions, Ada.Strings.Fixed;
use Ada.Float_Text_IO, Ada.Text_IO, Ada.Strings.Fixed;

procedure roots is

    A, B, C, root1, root2 : Float := 0.0;

------------------------------------------------
--  get_roots gets the roots of a quadratic equation.           
-- Receive: A, B, C, corresponding to quadratic equation values of the function        
-- PRE: A != 0, A^2 - 4AC > 0
--     (Ada arrays are 1-relative by default)
-- Passback: root1 - the first root,
--           root2 - the second root.
------------------------------------------------
function get_roots(A : in Float; B : in Float; C : in Float; root1 : out Float; root2 : out Float) return Boolean is
arg : Float;
begin
    if (A /= 0.0) then 
        -- calculate the discriminant
        arg := ((B ** 2) - (4.0 * A * C));
        -- make sure A is positive
        if (arg >= 0.0) then
            root1 := (-b + (Ada.Numerics.Elementary_Functions.Sqrt(arg)))/(2.0*a);
            root2 := (-b - (Ada.Numerics.Elementary_Functions.Sqrt(arg)))/(2.0*a);
            return true;

        else  -- discriminant is zero
            Put_Line("get_roots failed: b^2 - 4ac is negative!");
            root1 := 0.0; root2 := 0.0;
            return false;
        end if;
    else -- A is < zero
        Put_Line("get_roots failed: a is zero!");
        root1 := 0.0; root2 := 0.0;
        return false;
    end if;
end get_roots;

begin
    -- Get inputs of a, b, and c
    Put_Line("To get the roots of a quadratic function...");
    Put("Enter a: ");
    Get(A);
    Put("Enter b: ");
    Get(B);
    Put("Enter c: ");
    Get(C);

    if (get_roots(A, B, C, root1, root2) = true) then

        Put("The roots are: ");
        Put(root1);
        Put(" and ");
        Put(root2);

    end if;

end roots;]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ gnatmake roots
x86_64-linux-gnu-gcc-7 -c roots.adb
x86_64-linux-gnu-gnatbind-7 -x roots.ali
x86_64-linux-gnu-gnatlink-7 roots.ali
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ ./roots
To get the roots of a quadratic function...
Enter a: 2
Enter b: 2
Enter c: 2
get_roots failed: b^2 - 4ac is negative!
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ ./roots
To get the roots of a quadratic function...
Enter a: 0
Enter b: 2
Enter c: 2
get_roots failed: a is zero!
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ ./roots
To get the roots of a quadratic function...
Enter a: 1
Enter b: 4
Enter c: 4
The roots are: -2.00000E+00 and -2.00000E+00
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ ./roots
To get the roots of a quadratic function...
Enter a: 1
Enter b: 8
Enter c: 8
The roots are: -1.17157E+00 and -6.82843E+00
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ ./roots
To get the roots of a quadratic function...
Enter a: 1
Enter b: -5
Enter c: 6
The roots are:  3.00000E+00 and  2.00000E+00
]0;djv78@gold24: ~/CS214Work/214/projects/05/ada[01;32mdjv78@gold24[00m:[01;34m~/CS214Work/214/projects/05/ada[00m$ exit

Script done on 2020-03-09 19:05:40-0400
