Script started on 2020-04-27 16:50:00-0400
]0;djv78@gold03: ~/CS214Work/214/projects/10/java[01;32mdjv78@gold03[00m:[01;34m~/CS214Work/214/projects/10/java[00m$ cat [K[Kls
Bird.class   Birds.java  FlyingBird.class  Goose.java   Kiwi.java      Ostrich.java   Owl.java       WalkingBird.class
Bird.java    Duck.class  FlyingBird.java   java.script  Makefile       Ostritch.java  Penguin.class  WalkingBird.java
Birds.class  Duck.java   Goose.class       Kiwi.class   Ostrich.class  Owl.class      Penguin.java
]0;djv78@gold03: ~/CS214Work/214/projects/10/java[01;32mdjv78@gold03[00m:[01;34m~/CS214Work/214/projects/10/java[00m$ cat *.java
/* Bird.java provides a Bird class.
 *
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Completed by: Duncan Van Keulen
 * Date: 4/23/2020
 ******************************************************/

import java.io.*;

public class Bird
{

  /* default constructor
  * PostCond: myName == "".
  */

  public Bird() {
    myName = "";
  }


  /* explicit constructor
  * Receive: name, a String 
  * PostCond: myName == name.
  */

  public Bird(String name) {
    myName = name;
  }


  /* Name accessor
  * Return: myName.
  */

  public String getName() {
    return myName;
  }


  /* A Bird's Call
  * Return: a default bird-call ("Squawk!").
  */

  public String call() {
    return "Squaaaaaaaaaawk!";
  } 

  /* Output a Bird 
  * Output: Everything known about myself
  *          to the standard output stream.
  */

  public void print()
  {
    System.out.println( getName() + ' ' + getClass().getName() + " just " + movement()
                      + " and said " + call() );
  }

  public String movement() {
    return "existed";
  }



  private String myName;
}

/* Birds.java illustrates inheritance and polymorphism.
 *
 * Begun by: Joel Adams, for CS 214 Lab 10 at Calvin College.
 * Completed by: Duncan Van Keulen
 * Date: 4/23/2020
 *********************************************************/

public class Birds {
  
  public static void main(String[] args) {
    System.out.println("\nWelcome to the Bird Park!\n");

    Bird bird0 = new Bird();

    Bird bird1 = new Bird("Hawkeye");
    bird1.print();

    Duck bird2 = new Duck("Donald");
    bird2.print();

    Goose bird3 = new Goose("Mother Goose");
    bird3.print();

    Owl bird4 = new Owl("Woodsey");
    bird4.print();

    Penguin bird5 = new Penguin("Peter");
    bird5.print();
    
    Ostrich bird6 = new Ostrich("Orville");
    bird6.print();
    
    Kiwi bird7 = new Kiwi("Kathy");
    bird7.print();
    System.out.println();


  }
}

/* Duck.java provides a Duck subclass of Bird.
 *
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Completed by: Duncan Van Keulen
 * Date: 4/23/2020
 ******************************************************/

public class Duck extends FlyingBird {
    
  /* explicit constructor
  * Receive: name, a String 
  * PostCond: myName == name.
  */

  public Duck() {
    super();
  }

  public Duck(String name) {     
    super(name);
  } 



  /* A Duck's Call
  * Return: a duck-call ("Quack!").
  */

  public String call() {
    return "Quack!";
  } 
}

/* FlyingBird.java provides extends the bird class for flying birds
 *
 * By: Duncan Van Keulen
 * Date: 4/27/2020
 ******************************************************/

public class FlyingBird extends Bird {

    public FlyingBird() {
        super();
    }

    public FlyingBird(String name) {
        super(name);
    }

    public String movement() {
        return "flew by";
    }
}/* Goose.java provides a Goose subclass of Bird.
 *
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Completed by: Duncan Van Keulen
 * Date: 4/23/2020
 ******************************************************/

public class Goose extends FlyingBird {

  /* explicit constructor
  * Receive: name, a String 
  * PostCond: myName == name.
  */

  public Goose() {
    super();
  }

  public Goose(String name) {     
    super(name);
  } 

  /* A Goose's Call
  * Return: a goose-call ("Honk!").
  */

  public String call() {
    return "Honk!";
  }

} 

/* Kiwi.java provides an Kiwi subclass of WalkingBird.
 *
 * By: Duncan Van Keulen
 * Date: 4/27/2020
 ******************************************************/

public class Kiwi extends WalkingBird {

    /* explicit constructor
    * Receive: name, a String 
    * PostCond: myName == name.
    */

    public Kiwi() {
        super();
    }

    public Kiwi(String name) {
        super(name);
    }

    /* An Kiwi's Call
    * Return: an Kiwi-call ("Whoo-hoo!").
    */

    public String call() {
        return "Sqwee! Sqwee!";
    }

} 
/* Ostrich.java provides an Ostrich subclass of WalkingBird.
 *
 * By: Duncan Van Keulen
 * Date: 4/27/2020
 ******************************************************/

public class Ostrich extends WalkingBird {

    /* explicit constructor
    * Receive: name, a String 
    * PostCond: myName == name.
    */

    public Ostrich() {
        super();
    }

    public Ostrich(String name) {
        super(name);
    }

    /* An Ostrich's Call
    * Return: an Ostrich-call ("Whoo-hoo!").
    */

    public String call() {
        return "Snork!";
    }

} 
/* Owl.java provides an Owl subclass of Bird.
 *
 * Begun by: Prof. Adams, for CS 214 at Calvin College.
 * Completed by: Duncan Van Keulen
 * Date: 4/23/2020
 ******************************************************/

public class Owl extends FlyingBird {

  /* explicit constructor
  * Receive: name, a String 
  * PostCond: myName == name.
  */

  public Owl() {
    super();
  }

  public Owl(String name) {
    super(name);
  }


  /* An Owl's Call
  * Return: an owl-call ("Whoo-hoo!").
  */

  public String call() {
    return "Whoo hoo!";
  }

} 

/* Penguin.java provides an Penguin subclass of WalkingBird.
 *
 * By: Duncan Van Keulen
 * Date: 4/27/2020
 ******************************************************/

public class Penguin extends WalkingBird {

    /* explicit constructor
    * Receive: name, a String 
    * PostCond: myName == name.
    */

    public Penguin() {
        super();
    }

    public Penguin(String name) {
        super(name);
    }

    /* An Penguin's Call
    * Return: an Penguin-call ("Whoo-hoo!").
    */

    public String call() {
        return "Huh-huh-huh-huuuuh!";
    }

} 
/* WalkingBird.java provides extends the bird class for walking birds
 *
 * By: Duncan Van Keulen
 * Date: 4/27/2020
 ******************************************************/

public class WalkingBird extends Bird {
    public WalkingBird() {
        super();
    }

    public WalkingBird(String name) {
        super(name);
    }

    public String movement() {
        return "walked by";
    }
}]0;djv78@gold03: ~/CS214Work/214/projects/10/java[01;32mdjv78@gold03[00m:[01;34m~/CS214Work/214/projects/10/java[00m$ make
javac -deprecation Birds.java
]0;djv78@gold03: ~/CS214Work/214/projects/10/java[01;32mdjv78@gold03[00m:[01;34m~/CS214Work/214/projects/10/java[00m$ java Birds

Welcome to the Bird Park!

Hawkeye Bird just existed and said Squaaaaaaaaaawk!
Donald Duck just flew by and said Quack!
Mother Goose Goose just flew by and said Honk!
Woodsey Owl just flew by and said Whoo hoo!
Peter Penguin just walked by and said Huh-huh-huh-huuuuh!
Orville Ostrich just walked by and said Snork!
Kathy Kiwi just walked by and said Sqwee! Sqwee!

]0;djv78@gold03: ~/CS214Work/214/projects/10/java[01;32mdjv78@gold03[00m:[01;34m~/CS214Work/214/projects/10/java[00m$ exit

Script done on 2020-04-27 16:50:36-0400
