Script started on 2020-05-05 19:19:01-0400
]0;djv78@gold02: ~/CS214Work/code/labs/extraCredit[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/code/labs/extraCredit[00m$ clojure
Clojure 1.10.1
user=> (def squareSquare #(Math/pow (Math/pow % 2) 2))
#'user/squareSquare
user=> (squareSquare 5)
625.0
user=> (squareSquare 2)
16.0
user=> 
]0;djv78@gold02: ~/CS214Work/code/labs/extraCredit[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/code/labs/extraCredit[00m$ exit

Script done on 2020-05-05 19:20:48-0400
