Script started on 2020-02-27 16:46:24-0500
]0;djv78@gold07: ~/CS214Work/214/projects/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/ruby[00m$ cat factorial.rb 
#! /usr/bin/ruby
# factorial.rb displays the factorial of the input number
#
# By: Duncan Van Keulen on 2-27-2020
#
# Input: n, a number
# Precondition: n is positive
# Output: the factorial of n


if __FILE__ == $0
    # Get an integer input for each variable
    print "Enter a number n: "
    n = gets.chomp.to_f 
    i = 2
    answer = 1

    while (i <= n)
        answer = answer*i   # multiply to compute factorial
        i = i + 1           # increment i
    end

    puts("#{n}! = #{answer}") # output result
 
 end]0;djv78@gold07: ~/CS214Work/214/projects/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/ruby[00m$ ruby factorial.rb 
Enter a number n: 2
2.0! = 2
]0;djv78@gold07: ~/CS214Work/214/projects/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/ruby[00m$ ruby factorial.rb 
Enter a number n: 3
3.0! = 6
]0;djv78@gold07: ~/CS214Work/214/projects/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/ruby[00m$ ruby factorial.rb 
Enter a number n: 5
5.0! = 120
]0;djv78@gold07: ~/CS214Work/214/projects/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/projects/04/ruby[00m$ exit

Script done on 2020-02-27 16:47:47-0500
