Script started on 2020-03-05 13:43:32-0500
]0;djv78@gold21: ~/CS214Work/214/labs/05/java[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/java[00m$ cat Split.java
/* Split.java is a class and program that splits a string
 * into two substrings.
 * 
 * Begun by: Serita Nelesen
 * Completed by: Duncan Van Keulen on 3-5-2020
 ***************************************************************/

import java.util.Scanner;

// java class Split
public class Split {
  // main program
  public static void main(String[] args) {
    Scanner keyboard = new Scanner(System.in);
    // prompt for the string
    System.out.println("\nTo split a string, enter the string: ");
    String theString = keyboard.next();

    // prompt for splitting position
    System.out.println("\nEnter the split position: ");
    int position = keyboard.nextInt();

    // Create list, compute results and print
    String[] resultList = new String[2];
    splitter(theString, position, resultList);
    System.out.println("\nThe first part is " + resultList[0] + "\n and the second part is " + resultList[1]);

  }

  /*
   * splitter() splits a string according to the position specified Receive:
   * theString - the string to be split pos - the position at which to split
   * resList - an array of strings in which to place results
   *****************************************************/
  public static void splitter(String theString, int pos, String[] resList) {
    // Assign the first value of resList to the first part of the string
    resList[0] = theString.substring(0, pos);
    // Assign the second value of the resList to the second part of the string
    resList[1] = theString.substring(pos, theString.length());
  }

}
]0;djv78@gold21: ~/CS214Work/214/labs/05/java[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/java[00m$ javac -deprecation SPli[K[K[Kplit.java 
]0;djv78@gold21: ~/CS214Work/214/labs/05/java[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/java[00m$ java Split

To split a string, enter the string: 
hello

Enter the split position: 
0

The first part is 
 and the second part is hello
]0;djv78@gold21: ~/CS214Work/214/labs/05/java[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/java[00m$ java Split

To split a string, enter the string: 
hell0o  o

Enter the split position: 
3

The first part is hel
 and the second part is lo
]0;djv78@gold21: ~/CS214Work/214/labs/05/java[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/java[00m$ hello [K[Kjava Split

To split a string, enter the string: 
hello

Enter the split position: 
5

The first part is hello
 and the second part is 
]0;djv78@gold21: ~/CS214Work/214/labs/05/java[01;32mdjv78@gold21[00m:[01;34m~/CS214Work/214/labs/05/java[00m$ exit

Script done on 2020-03-05 13:44:48-0500
