Script started on 2020-04-16 17:50:18-0400
]0;djv78@gold02: ~/CS214Work/214/labs/09/ada[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/ada[00m$ make
gnatbind  max.ali
gnatlink  max.ali -o adaMax
]0;djv78@gold02: ~/CS214Work/214/labs/09/ada[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/ada[00m$ ./ma[K[KadaMax 
          99          88          77          66          55
          55          66          77          88          99
          55          77          99          88          66
The maximum value in list 1 is          99
The maximum value in list 2 is          99
The maximum value in list 3 is          99
]0;djv78@gold02: ~/CS214Work/214/labs/09/ada[01;32mdjv78@gold02[00m:[01;34m~/CS214Work/214/labs/09/ada[00m$ exit

Script done on 2020-04-16 17:50:28-0400
