Script started on 2020-02-27 15:20:04-0500
]0;djv78@gold07: ~/CS214Work/214/labs/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/ruby[00m$ cat rb[K[KlogTable.rb 
#! /usr/bin/ruby
# logTable.rb displays a table of logarithms
#
# Begun by: Prof. Adams, for CS 214 at Calvin College.
# Completed by: Duncan Van Keulen on 2-27-2020
#
# Input:  The start, stop and increment values
# Precondition: The start value is less than the stop value, 
#     and the increment is greater than 0
# Output: A table of logarithms from start to stop, with increment
#     as the step value


if __FILE__ == $0
   # Get an integer input for each variable
   print "Enter the start value: "
   start = gets.chomp.to_f 

   print "Enter the stop value: "
   stop = gets.chomp.to_f

   print "Enter the increment value: "
   increment = gets.chomp.to_f
   
   while (start <= stop)
      result = Math.log10(start)
      puts("The logarithm of #{start} is #{result}\n")
      start += increment
   end

end

]0;djv78@gold07: ~/CS214Work/214/labs/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/ruby[00m$ ruby logTable.rb 
Enter the start value: 1
Enter the stop value: 10
Enter the increment value: 0.5
The logarithm of 1.0 is 0.0
The logarithm of 1.5 is 0.17609125905568124
The logarithm of 2.0 is 0.3010299956639812
The logarithm of 2.5 is 0.3979400086720376
The logarithm of 3.0 is 0.47712125471966244
The logarithm of 3.5 is 0.5440680443502757
The logarithm of 4.0 is 0.6020599913279624
The logarithm of 4.5 is 0.6532125137753437
The logarithm of 5.0 is 0.6989700043360189
The logarithm of 5.5 is 0.7403626894942439
The logarithm of 6.0 is 0.7781512503836436
The logarithm of 6.5 is 0.8129133566428556
The logarithm of 7.0 is 0.8450980400142568
The logarithm of 7.5 is 0.8750612633917001
The logarithm of 8.0 is 0.9030899869919435
The logarithm of 8.5 is 0.9294189257142927
The logarithm of 9.0 is 0.9542425094393249
The logarithm of 9.5 is 0.9777236052888477
The logarithm of 10.0 is 1.0
]0;djv78@gold07: ~/CS214Work/214/labs/04/ruby[01;32mdjv78@gold07[00m:[01;34m~/CS214Work/214/labs/04/ruby[00m$ exit

Script done on 2020-02-27 15:20:22-0500
