Script started on 2020-02-13 15:20:17-0500
]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ cat example6.lex
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity                return TOKHUMIDITY;
to                      return TOKTO;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ cat example.y
cat: example.y: No such file or directory
]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ cat example.y6.y
%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */ 
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}
 
int yywrap() {
        return 1;
} 
 
int main() {
        yyparse();
} 

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY TOKTO
%%

commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set 
        | humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;

temperature_set:
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;

humidity_set:
        TOKSET TOKHUMIDITY TOKTO NUMBER
        {
                printf("\tHumidity set to %d\n",$4);
        }
        ;]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ flex example6.lex
]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ bison -d example6.y
]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ gcc lex.yy.c example6.tab.c -o example6
]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ ./example6
heat on
	Heat turned on
set temperature 57
	Temperature set to 57
set temperature 71
	Temperature set to 71
set     heat off
	Heat turned off
set humidity to 26
	Humidity set to 26

Thanks, love you Hyechan!!!
]0;djv78@gold25: ~/214/labs/02[01;32mdjv78@gold25[00m:[01;34m~/214/labs/02[00m$ exit

Script done on 2020-02-13 15:24:18-0500
